### ISSUE TITLE
 Invalid character escape '\s'.

### ISSUE THREAD

**Issue by machinezhou** [konovalov-k/Android-Filament-C-Example#1]
**hi would you mind take a look at my failure log? I cannot build this project correctly.**

E:\sourcecode\Android-Filament-C-Example-main\app_filament_980\src\main\cpp\CMakeLists.txt : C/C++ debug|x86 : CMake Error at E:\sourcecode\Android-Filament-C-Example-main\app_filament_980\src\main\cpp\CMakeLists.txt:4 (add_library):
  Syntax error in cmake code when parsing string

    E:\sourcecode\Android-Filament-C-Example-main\app_filament_980/src/main/cpp/filament/cpp/IBL.cpp

  Invalid character escape '\s'.

E:\sourcecode\Android-Filament-C-Example-main\app_filament_980\src\main\cpp\CMakeLists.txt : C/C++ debug|x86 : CMake Error at E:\sourcecode\Android-Filament-C-Example-main\app_filament_980\src\main\cpp\CMakeLists.txt:4 (add_library):
  Syntax error in cmake code when parsing string

    E:\sourcecode\Android-Filament-C-Example-main\app_filament_980/src/main/cpp/filament/cpp/MaterialGenerator.cpp

  Invalid character escape '\s'.

E:\sourcecode\Android-Filament-C-Example-main\app_filament_980\src\main\cpp\CMakeLists.txt : C/C++ debug|x86 : CMake Error at E:\sourcecode\Android-Filament-C-Example-main\app_filament_980\src\main\cpp\CMakeLists.txt:4 (add_library):
  Syntax error in cmake code when parsing string

    E:\sourcecode\Android-Filament-C-Example-main\app_filament_980/src/main/cpp/android/Path.cpp

  Invalid character escape '\s'.

E:\sourcecode\Android-Filament-C-Example-main\app_filament_980\src\main\cpp\CMakeLists.txt : C/C++ debug|x86 : CMake Error at E:\sourcecode\Android-Filament-C-Example-main\app_filament_980\src\main\cpp\CMakeLists.txt:4 (add_library):
  Syntax error in cmake code when parsing string

    E:\sourcecode\Android-Filament-C-Example-main\app_filament_980/src/main/cpp/android/CallbackUtils.cpp

  Invalid character escape '\s'.

E:\sourcecode\Android-Filament-C-Example-main\app_filament_980\src\main\cpp\CMakeLists.txt : C/C++ debug|x86 : CMake Error at E:\sourcecode\Android-Filament-C-Example-main\app_filament_980\src\main\cpp\CMakeLists.txt:4 (add_library):
  Syntax error in cmake code when parsing string

    E:\sourcecode\Android-Filament-C-Example-main\app_filament_980/src/main/cpp/android/NioUtils.cpp

  Invalid character escape '\s'.

E:\sourcecode\Android-Filament-C-Example-main\app_filament_980\src\main\cpp\CMakeLists.txt : C/C++ debug|x86 : Configuration failed.

**Comment by k-konovalov** [comment]
Hi @machinezhou. Looks like you trying to build project in Windows?
> E:\sourcecode\Android-Filament-C-Example-main\app_filament_980/src/main/cpp/filament/cpp/IBL.cpp

Double check the slash - I built it in macOs (unix based path).
See - [this](https://superuser.com/questions/176388/why-does-windows-use-backslashes-for-paths-and-unix-forward-slashes)

**Comment by k-konovalov** [comment]
Closed due inactivity
